added ShoppingCart model
furthernull/book-store pull request #11
Opened 2024-06-19 04:33 UTC by furthernull

2024-06-19 06:00 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +            @RequestBody @Valid CartItemRequestDto requestDto,
```suggestion
            @RequestBody @Valid UpdateCartItemDto requestDto,
```

Create UpdateCartItemDto where int quantity

2024-06-19 06:03 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/service/impl/CartItemServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Can't retrieve CartItem by id's"));
```suggestion
                .map(item -> {
                    item.setQuantity(requestDto.quantity());
                    return item;
                }).orElseThrow(() -> new EntityNotFoundException(
                        String.format("No cart item with id: %d for user: %d", cartItemId, userId)
                ));
        cartItemRepository.save(cartItem);
        return cartMapper.toDto(cart);
```

2024-06-19 06:04 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/service/impl/CartItemServiceImpl.java
> +        cartItem.setShoppingCart(shoppingCart);
What if shoppingCart already has the same book by Id, we need to increase quantity. 
If no, add cartItem to cart.

2024-06-19 06:04 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/service/impl/CartItemServiceImpl.java
> +    private final BookRepository bookRepository;
Replace all logic to ShoppingCartServiceImpl

2024-06-19 06:05 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/09-create-shopping-carts-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```
Add empty line at the end of each changelog

2024-06-19 06:08 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/mapper/BookMapper.java
>      void updateModel(@MappingTarget Book book, BookRequestDto requestDto);
Do you really need nullValuePropertyMappingStrategy for each field?

2024-06-23 12:35 UTC, okuzan requested changes

2024-06-23 12:35 UTC, okuzan commented on src/main/java/com/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        Long userId = ((User) authentication.getPrincipal()).getId();
deal with it on controller level, don't pass authentication to the service, create a private method for repeated logic

2024-06-24 05:55 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments

2024-06-25 07:08 UTC, Elena-Bruyako approved these changes
Good job!

2024-07-06 15:50 UTC, merged