JpaRepository, Liquibase support, soft delete concept, expanded controller capability
furthernull/book-store pull request #3
Opened 2024-04-06 03:52 UTC by furthernull

2024-04-06 10:40 UTC, olekskov requested changes

2024-04-06 10:40 UTC, olekskov commented on src/main/java/com/example/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
As per my understanding of the use case we may expect if somebody wish to update single field in book he will pass only that field. Others will obtain null values during serialization.
Think we should take that into account in order not to override majority of fields with null values while user just wanted them to remain unchanged

2024-04-07 11:09 UTC, okuzan requested changes

2024-04-07 11:09 UTC, okuzan commented on src/main/java/com/example/bookstore/model/Book.java
> +@SQLRestriction("is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction("is_deleted = FALSE")
```

2024-04-07 11:09 UTC, okuzan commented on src/main/java/com/example/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
valid point, use MapStruct to do it elegantly

2024-04-08 11:06 UTC, Rommelua approved these changes

2024-04-08 22:44 UTC, merged