added ability to search books
furthernull/book-store pull request #4
Opened 2024-04-12 05:03 UTC by furthernull

2024-04-12 10:22 UTC, MAMentorFX requested changes

2024-04-12 10:22 UTC, MAMentorFX commented on src/main/java/com/example/bookstore/service/impl/BookServiceImpl.java
> +                .toList();
Mapstruct supports mapping collections from the box

2024-04-12 10:22 UTC, MAMentorFX commented on src/main/java/com/example/bookstore/repository/book/BookSpecificationBuilder.java
> +        }
too similar code, try to think how you can upgrade it

2024-04-14 16:28 UTC, okuzan approved these changes

2024-04-14 16:28 UTC, okuzan commented on src/main/java/com/example/bookstore/repository/book/BookSpecificationProviderManager.java
> +                .filter(p -> p.getKey().equals(key))
change p to provider, avoid uninformative naming

2024-04-14 19:33 UTC, merged