added User entity, related repository, mapper, DTOs, and a registration endpoint
furthernull/book-store pull request #7
Opened 2024-05-25 15:23 UTC by furthernull

2024-05-26 05:16 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2024-05-26 05:16 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/repository/user/UserRepository.java
> +    Optional<User> findByEmail(String email);
It's better to add `boolean existsByEmail(String email);`

2024-05-26 05:16 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.getEmail()).isPresent()) {
It's better to use this implementation, to avoid calling isPresent()
```suggestion
        if (userRepo.existsByEmail(request.email())) {
            throw new RegistrationException(
                    String.format("User with this email: %s already exists", request.email())
            );
        }
```

2024-05-26 05:16 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/service/impl/UserServiceImpl.java
> +        newUser.setEmail(requestDto.getEmail());
You can use MapStruck here
User user = mapper.toUser(request);

2024-05-26 05:16 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/service/impl/UserServiceImpl.java
> +        User savedUser = userRepository.save(newUser);
```suggestion
        userRepository.save(user);
        return userMapper.toDto(user);
```

2024-05-26 05:16 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/dto/user/UserRegistrationRequestDto.java
> +    @NotBlank
Please, add Length here also

2024-05-26 05:16 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-user-table.yaml
> +                  type: varchar(255)
In RequestDto you have another length values

2024-05-27 05:11 UTC, Elena-Bruyako approved these changes
Approve, but pay attention to the comment

2024-05-27 05:11 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/model/User.java
> +    @Column(name = "first_name", nullable = false)
You actually don't need to specify column name, Hibernate manages it by converting field name to column using snake_case

2024-05-27 05:22 UTC, furthernull commented on src/main/java/com/example/bookstore/model/User.java
> +    @Column(name = "first_name", nullable = false)
thanks, my mistake. i will fix it

2024-05-27 05:25 UTC, merged